name: Modify Linux build files

on:
  push:
    tags:
      - '*.*.*'

jobs:
  update-build-files:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Update RPM specfile
      # Build your program with the given configuration
      run: |
        sed -i "s/Version:.*/Version:\t\t${{ steps.get_version.outputs.version-without-v }}/" rpm/klm.spec

    - name: Update deb config
      run: |
        sudo apt-get update
        sudo apt-get install devscripts
        dch -D bionic -v ${{ steps.get_version.outputs.version-without-v }}-1~bionic "Automatc update from github tag"
        dch -r "Autobuild from git commit"

    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
          file-path: |
              rpm/klm.spec
          commit-msg: Update version from git tag
          github-token: ${{ secrets.GITHUB_TOKEN }}
