name: Modify Linux build files

on:
  push:
    tags:
      - '*.*.*'

jobs:
  update-build-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Update RPM specfile with git tag version
        # Build your program with the given configuration
        run: |
          sed -i "s/Version:.*/Version:\t\t${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}/" rpm/klm.spec
          sed -i "s/Source0:.*/Source0:\thttps:\/\/github.com\/ILightburn\/KLM\/releases\/download\/${{ steps.get_version.outputs.version }}\/klm-${{ steps.get_version.outputs.version-without-v }}.tar.gz/" rpm/klm.spec
#      - name: Update deb config
#        run: |
#          sudo apt-get update
#          sudo apt-get install devscripts
#          dch -D bionic -v ${{ steps.get_version.outputs.version-without-v }}-1~bionic "Automatc update from github tag"
#          dch -r "Autobuild from git commit"

      - name: Create fedora tarball
        run: |
          cd ..
          cp -R KLM klm-${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}
          cd klm-${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}
          git submodule update --init
          cd ..
          tar -zcf klm-${{ steps.get_version.outputs.version-without-v }}.tar.gz klm-${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}.${{ steps.get_version.outputs.patch }}
          mv klm*.tar.gz KLM/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "klm-${{ steps.get_version.outputs.version-without-v }}.tar.gz"
          prerelease: ${{ contains(steps.get_version.outputs.prerelease, 'alpha') || contains(steps.get_version.outputs.prerelease, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes to repo
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            rpm/klm.spec
          commit-msg: Update version from git tag
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger COPR build
        run: |
          curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/16440/a71138a2-bc88-4b77-8af0-bc3b1697ac35/klm/

