name: Windows 32bit Build

on:
  push:
    branches: [ main ]

jobs:
  build64:
    name: Windows 32bit Build
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Cache Qt
        id: cache-qt
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache-5.15.2-1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: '5.15.2'
          modules: 'core'
          arch: win32_msvc2019

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x86

      - name: Configure CMake
        shell: cmd
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build .

      - name: Create output dir and copy exe
        run: |
          mkdir output
          copy build\klm.exe output\

      - name: Run windeployqt
        run: |
          windeployqt --release --compiler-runtime output/klm.exe
          dir output
        shell: cmd

      - name: Create zipfile
        run: |
          7z a klm-windows-32bit.zip output

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: Win64 test build
          path: klm-windows-32bit.zip
