name: Windows 64bit Build

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build64:
    name: Windows 64bit Build
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Put version tag in the environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Cache Qt
        id: cache-qt
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: "D:/a/KLM/Qt"
          key: ${{ runner.os }}-Qt64Cache-5.15.2-1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: '5.15.2'
          modules: 'core'

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Configure CMake
        shell: cmd
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build .

      - name: Create output dir and copy exe and deps
        run: |
          mkdir output
          copy build\klm.exe output\
          copy LICENSE output\license.txt
          copy icons\klm.ico output\klm.ico
          windeployqt --release --compiler-runtime output/klm.exe

      - name: Create Installer
        run: |
          cp windows\klm-x86_64.iss inst.iss
          sed -i "s/#define MyAppVersion.*/#define MyAppVersion \"${{ env.RELEASE_VERSION }}\"/" cd/inst.iss
          mkdir installer
          "c:/Program Files (x86)/Inno Setup 6/iscc.exe" inst.iss /Oinstaller\
        shell: bash

      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: Win64 test build
          path: installer

      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.gcp_credentials }}
          path: "installer/OpenKJ-KLM-${{ env.RELEASE_VERSION }}.exe"
          destination: openkj-installers/klm/